spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=head_hunter_data
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/db/changelog/master.xml
    enabled: true
    drop-first: false